---
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
 License: Apache-2.0
Description: This template creates 2 iam roles for codedeploy and an instance profile.

Resources:
# IAM role for ec2 code deploy and amazon s3 
  IamRoleEc2CodeDeployS3:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: Ec2RoleForCodeDeployS3
      Description: EC2 IAM role for AWS code Deploy access and S3 full access
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
  
  IamRoleCodeDeploy:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: RoleForCodeDeploy
      Description: IAM role for AWS code Deploy access and S3 full access
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole'
       
  IamRoleEc2CodeDeployS3InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: Ec2CodeDeployS3RoleInstanceProfile
      Roles:
        - Ref: IamRoleEc2CodeDeployS3

Outputs:
  EC2CodeDeployS3Role:
    Description: IamRoleEc2CodeDeployS3 arn
    Value: !GetAtt IamRoleEc2CodeDeployS3.Arn #!Ref IamRoleEc2CodeDeployS3
    Export:
      Name: !Sub '${AWS::StackName}-IamRoleEc2CodeDeployS3Arn'
    
  CodeDeployRole:
    Description: IamRoleCodeDeploy arn
    Value: !GetAtt IamRoleCodeDeploy.Arn
    Export:
      Name: !Sub '${AWS::StackName}-IamRoleCodeDeployArn'

  EC2CodeDeployS3RoleInstanceProfile:
    Description: IamRoleCodeDeploy instance profile 
    Value: !Ref IamRoleEc2CodeDeployS3InstanceProfile
    Export:
      Name: !Sub '${AWS::StackName}-Ec2CodeDeployS3InstProfileName'
  